### ISSUE TITLE
Great-Thank You

### ISSUE THREAD

**Issue by SheepDomination** [James-N/vscode-osl#1]
Thank you for doing this, I was thinking of creating a syntax highlighter for OSL but didn't know how to go about it; which brings me to the question, how do you create such an extension ? 
Is it possible to have this hooked into Octane Standalone ?

**Comment by James-N** [comment]
I didn't "create" the syntax highlighter, the syntax highlighting framework is built inside vs-code, and the only thing I need to do is to provide the syntax definition file.  The syntax definition file, which is the .tmlanguage file, is based on the TextMate syntax highlighting protocol. And for OSL, since it shares most language features with C, I used the official syntax definition for C as reference. 
For your second question, I don't know too much about Octane Standalone. If your are asking about the workflow, then usually software like blender or v-ray that supports OSL can load in an external source file and compile it automatically. In this way, you can simply edit the code in vscode, save it, and let the software recompile it for you.

**Comment by SheepDomination** [comment]
Since you developed this extension; I was thinking since Octane as well as other engines support OSL, if I can write the code in VSCode then it would send it do the node, in this case with regards to Octane Standalone to the OSL Node; something I'll look into. 

In the meantime, you find the syntax definition file for C, then you edit the file, if I understand correctly ?

**Comment by James-N** [comment]
The term “send it to the node” could be a little bit tricky in practical use, if the engine could load in external files, usually it could watch the file changing and update the shader on the fly, which is exactly what you want. Some software like Houdini can edit internal code in external editor, which makes it much easier. But if the engine you are using doesn't support any of above, whether you can adopt the workflow depends on the engine API; like in Maya, you can open a pipe in the commandline and send data to it. For Octane, I guess you should check the official development doc first :)
About how I created the syntax definition, it's basically what you said.

**Comment by SheepDomination** [comment]
I plan on getting some Lua basics as I know Octane uses Lua; maybe, with the aid of Lua, it can be done.  Let me follow this up in a few days.
